### ISSUE TITLE
bug: new SafeConnector throws error

### ISSUE THREAD

**Issue by mihoward21** [wagmi-dev/references#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Get the following error on my call to new SafeConnector:

`TypeError: SafeAppsSDK is not a constructor`

### Expected Behavior

Should instantiate with no error.

### Steps To Reproduce

```
import { configureChains, createClient } from 'wagmi'
import { mainnet, goerli } from 'wagmi/chains'
import { SafeConnector } from 'wagmi/connectors/safe'
import { publicProvider } from 'wagmi/providers/public'

const { chains, provider } = configureChains(
  [mainnet, goerli],
  [publicProvider()],
)

const client = createClient({
  autoConnect: false,
  connectors: [
    // Error is thrown here
    new SafeConnector({
      chains,
    }),
    new MetaMaskConnector({
      chains,
    }),
  ],
  provider,
})
```

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

[Codesandbox](https://codesandbox.io/p/github/mihoward21/wagmi-test/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522cle2dwdap000bfvgpazrw537w%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cle2dwewz000x3b6uvkep4qvz%2522%253A%257B%2522key%2522%253A%2522cle2dwewz000x3b6uvkep4qvz%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522cle2dwex0000y3b6u0tq5htyr%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cle2dxpdz008x3b6u0lz5t2w5%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cle2dxofa006t3b6uuhzobya1%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cle2dwewz000x3b6uvkep4qvz%2522%252C%2522spacesOrder%2522%253A%255B%2522cle2dwewz000x3b6uvkep4qvz%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

### Anything else?

This is in a nextjs app. I'll try to get a minimal reproducible example app up later today.

**Comment by tmm** [comment]
> I'll try to get a minimal reproducible example app up later today.

Awesome! Random question: Are you using Vite?

**Comment by cruzdanilo** [comment]
i'm having the same error. using next.

**Comment by mihoward21** [comment]
@tmm no not using vite. Just added a codesandbox link. You'll see it fails to load the app. That's just a generic nextjs react app, only changes I made were to add some wagmi code in `pages/index.js`.

**Comment by tmm** [comment]
@mihoward21 the CodeSandbox link is dead. Can you double check that it works (e.g. not private, exists)?

**Comment by tmm** [comment]
Just tried to reproduce and wasn't able so once that CodeSanbox is accessible. Please let me know and I'll re-open this issue.

**Comment by mihoward21** [comment]
@tmm sorry about that, having some trouble with the codesandbox permissions. Here's a github link if it helps, I'll try to get the codesandbox fixed up so it's accessible
https://github.com/mihoward21/wagmi-test

**Comment by tmm** [comment]
Was able to reproduce and have a fix up so no worries!
