### ISSUE TITLE
auroraTestnet can`t be added

### ISSUE THREAD

**Issue by valeriofichera** [wagmi-dev/references#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to add auroraTestnet from wagmi/chains it returns following error:

Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/wagmi_chains.js?v=7431360a' does not provide an export named 'auroraTestnet' 

### Expected Behavior

should not give an error

### Steps To Reproduce

import { goerli,
         polygonMumbai,
         auroraTestnet
        } from "wagmi/chains";
        
        //.....
        
        const { chains, provider } = configureChains(
    [goerli,
     polygonMumbai,
     auroraTestnet
     
    ],

    [infuraProvider({ apiKey: 'myKey'}),
     publicProvider()]
  );

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a https://new.wagmi.sh?

Will re-open when done.
