### ISSUE TITLE
bug: Uncaught Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by web3dopamine** [wagmi-dev/references#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While making use of `useEnsName` hook in Wagmi, i am getting the error : Uncaught Error: No QueryClient set, use QueryClientProvider to set one

the following is the snippet used for calling the hook
` const { data: ensName, isError, isLoading } = useEnsName({
    address: '0x93905fd3f9b8732015f2b3Ca6c16Cbcb60ECf895',
    onError(error) {
        console.log('Error', error)
      },
  })`
  
  

### Expected Behavior

should give ENS name for the address : 0x93905fd3f9b8732015f2b3Ca6c16Cbcb60ECf895

### Steps To Reproduce

Just following `useEnsName` hook guide in docs

### Anything else?

![image](https://user-images.githubusercontent.com/14943387/224475261-6a92a781-c4e5-4e52-99cb-816d3e34334c.png)

**Comment by jxom** [comment]
Have you wrapped your app inside a [`WagmiConfig`](https://wagmi.sh/react/WagmiConfig)?

If you have, can you please provide a minimal reproducible example via https://new.wagmi.sh? 

Will re-open when provided.

**Comment by web3dopamine** [comment]
![image](https://user-images.githubusercontent.com/14943387/225248006-8df5e0d1-dedb-4186-86f7-2a3314b223c9.png)

I did wrap it, okay will provide example in https://new.wagmi.sh/

**Comment by web3dopamine** [comment]
https://codesandbox.io/p/sandbox/agitated-feather-5b1xc5?file=%2Fsrc%2FApp.tsx

Check this out!
