### ISSUE TITLE
bug: UNSTABLE_shimOnConnectSelectAccount is true and metamask is already open not rejected error

### ISSUE THREAD

**Issue by siosio34** [wagmi-dev/references#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i want to error handling connect when already metamask opened.
but when UNSTABLE_shimOnConnectSelectAccount is true no ResourceUnavailable  error throw
i found when UNSTABLE_shimOnConnectSelectAccount is true, only throw UserRejectedRequestError.
why not throw ResourceUnavailable error ?

my code and metamask file code image below

![image](https://user-images.githubusercontent.com/7166022/225266475-665f5ce5-3069-4618-b708-9b5d0059abc7.png)

```
async function connectWallet() {
    try {
      const connectResult = await connectAsync()

      return Promise.resolve(connectResult)
    } catch (e) {

      if (e.name === 'ResourceUnavailable') {
        return
      }


      if (e.name === 'UserRejectedRequestError') {
        // TODO 예외사항처리필요
        return
      }


    }
  }
  ```

### Expected Behavior

when UNSTABLE_shimOnConnectSelectAccount true and metamask already open throw error

**Comment by jxom** [comment]
I am unsure what you mean here. We throw a `UserRejectedRequestError` when a user rejects the connection request. Why would we throw a ResourceUnavailable error? Can you please provide some more details here.

**Comment by siosio34** [comment]
I want to show the user an error saying metamask is already open when metamask is already open.
In Metamask, in that case, the error code is -32002 and the name is ResourceUnavailable. 
However, wagmi only throws errors for UserRejectedRequestError,  I can't notify the user of an error when metamask is already on.


So I want do not throw only UserRejectedRequestError, if metamask is already turned on and the error occur , that error throw too @jxom

**Comment by siosio34** [comment]
@tmm thanks!
