### ISSUE TITLE
(MetaMask) getProvider should handle cases where ethereum is not immediately injected

### ISSUE THREAD

**Issue by Meemaw** [wagmi-dev/references#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If for some reason extension doesn't immediately inject the `window.ethereum` object, connector will miss the update. This leads to a broken experience, because even though the user has the extensions, UI will act like they don't.

### Expected Behavior

Should better handle the async nature of extension injection. I suggest something like https://github.com/MetaMask/detect-provider is used, which is built for exactly this reason.

### Steps To Reproduce

This is hard to reproduce in an isolated environment, but I can reproduce this consistently when using a bunch of extensions (e.g Phantom, Solflare, and other wallets...)

**Comment by BatuhanK** [comment]
same issue here +1

**Comment by nazihkalo** [comment]
facing same issue :/

**Comment by jxom** [comment]
Hmm yeah, seems like we may need to [make `ready` async](https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/injected.ts#L89).

**Comment by BatuhanK** [comment]
> Hmm yeah, seems like we may need to [make `ready` dynamic](https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/injected.ts#L89).
> 
> For the meantime, you could do `Boolean(await connector.getProvider())` over `connector.ready` – this is essentially the same thing, except that `getProvider` is called dynamically.

hello @jxom thanks for quick reply.

will you guys publish a hotfix or should we create a patch locally in our repos?

**Comment by jxom** [comment]
Can you not do `Boolean(await connector.getProvider())` for now until you wait for a fix on our end?

**Comment by 0xFayzer** [comment]
not working for me

**Comment by BatuhanK** [comment]
> Can you not do `Boolean(await connector.getProvider())` for now until you wait for a fix on our end?
sorry to ping you again but I dont have deep knowledge on how wagmi's internals work, where should I put that hotfix?

```js

const { chains, provider } = configureChains(
  [mainnet],
  [
    alchemyProvider({ apiKey: "" }),
    publicProvider()
  ]
);

const { connectors } = getDefaultWallets({
  appName: "ERA",
  chains
});

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider
});

```
tried to implement this on our codebase but I failed

**Comment by 0xFayzer** [comment]
I also add that the problem appears for me only in production mode (when I build) and not in development mode

**Comment by 0xFayzer** [comment]
> Can you not do `Boolean(await connector.getProvider())` for now until you wait for a fix on our end?

I just put true instead of connector.ready but it doesn't work

**Comment by Meemaw** [comment]
Was able to temporary fix this using https://github.com/ds300/patch-package, and the following patch:

<img width="1173" alt="Screenshot 2023-03-15 at 21 32 20" src="https://user-images.githubusercontent.com/8524109/225435306-416be2e3-f2fd-4883-bcc0-e9664432115e.png">

Tried to open a PR with this change, but it seems it actually doesn't play well with the sync nature of connector constructors.

**Comment by BatuhanK** [comment]
> Was able to temporary fix this using https://github.com/ds300/patch-package, and the following patch:
> 
> <img alt="Screenshot 2023-03-15 at 21 32 20" width="1173" src="https://user-images.githubusercontent.com/8524109/225435306-416be2e3-f2fd-4883-bcc0-e9664432115e.png">
> 
> Tried to open a PR with this change, but it seems it actually doesn't play well with the sync nature of connector constructors.

can you share your patch file please on gist

**Comment by Meemaw** [comment]
https://gist.github.com/Meemaw/f7a17a6eaf5e8cd2a226377f5b022395

**Comment by glitch-txs** [comment]
This issue is related to [manifest v3](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/ib-hi7hPdW8/m/34mFf8rrGQAJ?pli=1). MetaMask [utilizes an event for this](https://github.com/MetaMask/detect-provider/blob/9dc0085245a162ec7c5a856fefac4ce1eb334b70/src/index.ts#L50). Trust Wallet does the same thing, I've also seen some libraries adding a Timeout of a couple of ms

**Comment by tmm** [comment]
This is out of scope for the current version of Wagmi and will be solved in the next major version.
