### ISSUE TITLE
bug: Metamask not opening automatically on triggering Wagmi write function on Mobile

### ISSUE THREAD

**Issue by Mohamed-kassim** [wagmi-dev/references#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.4

### Current Behavior

on triggering write action from Wagmi for any available contract methods, Meta mask not opening, need to open it manually and then accept the transaction there.
this is only happening on Mobile android and IOS, the web is working perfectly.

### Expected Behavior

write action should open or switch to meta mask as the wallet is already connected.

### Steps To Reproduce

- connect wallet through meta mask
- Run any write action in your contract

Try Wagmi write example in the docs, also not working on mobile

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

Which WalletConnect Connector are you using?

**Comment by Mohamed-kassim** [comment]
@tmm I am using Rainbow kit 0.12.2, minimal reproducing is required deploying to HTTPS to test on mobile 
but even https://wagmi.sh/examples/contract-write sample is not working

**Comment by tmm** [comment]
Got it. This likely has something to do with the different WalletConnect Connector versions (e.g. `WalletConnectConnector` and `WalletConnectLegacyConnector`).

If you can put together a minimal reproducible example with just wagmi (no RainbowKit), then I can look into it ASAP.
