### ISSUE TITLE
bug: WalletConnectConnector throws uncaught error on switchNetwork init failure

### ISSUE THREAD

**Issue by ryanberckmans** [wagmi-dev/references#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With slingshot mobile wallet (that does not support the test network I'm trying to switch to), the following error occurs on `useSwitchNetwork(...).switch` construction:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/299324/227225667-fa3943a2-8df0-4b95-9678-9745a597f203.png">

Throw source: https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/walletConnect.ts#L254

### Expected Behavior

The error should be handled internally by wagmi, and result in setting `useSwitchNetwork(...).isError` to `true`, and `useSwitchNetwork(...).error` to a useful error.

### Steps To Reproduce

1. download slingshot mobile wallet
2. ask it to switch to an unsupported network using `useSwitchNetwork`

### Anything else?

In general, wagmi should consider hiring a plucky intern (perhaps from [Waterloo](https://uwaterloo.ca/hire/) to work on testing and bugfixing the matrix of (all popular wallets) x (wallet-specific error cases). 

Of course, mobile wallet support is very important as we move into this next phase of growing crypto to global ubiquity.

Popular mobile wallets include
- rainbow
- coinbase wallet
- metamask mobile
- slingshot

Wallet-specific error cases for the intern to cover include
- switch network construction
- switch network rejection by user
- add network rejection by user
- transaction sign rejection by user
- unaffordability of gas fee (note interaction with account abstraction)

**Comment by jxom** [comment]
I tried to reproduce this, but was successfully able to catch the error within `useSwitchNetwork` with `isError`, `error`, etc. 

Mind creating a minimal reproducible example via https://new.wagmi.sh so we can look into it? Will re-open when done.
