### ISSUE TITLE
bug: WalletConnectLegacyConnector used wrong RPC url

### ISSUE THREAD

**Issue by darthmeme** [wagmi-dev/references#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

`@wagmi/core` - `0.10.2`

### Current Behavior

When connecting a wallet (in my case Metamask) on mobile using the WalletConnect legacy connector and performing any sort of transaction - a request will be made to `https://mainnet.infura.io/v3/undefined` and fail. You can see in the code below, the only chain that was defined was `polygonMumbai`.

I've found a workaround using the following:
```ts
const walletConnectProvider = await client.connector?.getProvider()
const chainId = await client.connector.getChainId()
walletConnectorProvider.http = walletConnectProvider.setHttpProvider(chainId)
```

This seems to fix it and requests now go to `https://matic-mumbai.chainstacklabs.com`.

All of this was done using the `publicProvider()`. Unfortunately, there's a related second issue where if instead of the `publicProvider`, I use the `alchemyProvider()` with a proper api key, the request still goes to chainstacklabs.

### Expected Behavior

I expect the request to go to the correct RPC url depending on the chain & providers defined in `configureChains` without the need of a workaround.

### Steps To Reproduce

```ts
const chains = [polygonMumbai]

const { provider } = configureChains(chains, [
  publicProvider()
])

export const client = createClient({
  autoConnect: true,
  provider,
  connectors: [
    new WalletConnectLegacyConnector({
      chains,
      options: {},
    }),
  ],
})

await connect({ connector: client.connectors[0] })

// Do some action like sendTransaction or writeContract here
```

### Anything else?

Related issues:
https://github.com/wagmi-dev/wagmi/issues/116
https://github.com/wagmi-dev/wagmi/issues/365

**Comment by darthmeme** [comment]
@KevinLu Thanks for the suggestion - I'll try it out!

Although, doesn't that kind of defeat the purpose of the alchemy / infura providers?

**Comment by jxom** [comment]
I think the issue here is that the wallet you are connecting to does not support the Polygon Mumbai network, so WalletConnect falls back to Mainnet (which it cannot find an RPC URL for as it is not in your configured chains). However, I believe it should fall back to the unsupported chain's RPC URL as public RPC methods should still work (I'd expect it to use that over mainnet anyway.

Fix at #196.

**Comment by darthmeme** [comment]
@jxom - I'm not sure if you might have missed it, but I mention that I'm using MetaMask which does support Polygon Mumbai

**Comment by jxom** [comment]
Looks like WC is doing something else strange then :D

**Comment by darthmeme** [comment]
@jxom - Just saw your PR -  the workaround does fix the mainnet issue, but using the alchemy or infura provider still doesn't work as expected and will still go to the public RPC url rather than alchemy or infura URLs.

This issue should probably remain opened.

**Comment by haani** [comment]
Seeing this issue as well. `WalletConnectLegacyConnector` always uses the default/public RPC url regardless of the provider configuration.

**Comment by AsiaMartini** [comment]
Same problem here:

"Using the alchemy or infura provider still doesn't work as expected and will hit the public RPC url rather than alchemy or infura's URL."
