### ISSUE TITLE
bug: Walletconnect Desktop Options are Hidden

### ISSUE THREAD

**Issue by frankfka** [wagmi-dev/references#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.6

### Current Behavior

In the examples, I see that the desktop wallets are shown:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/31530056/228021761-e729467a-73a1-4d86-a9f4-ace5366086e0.png">

However, using the standard configuration of:
```
new WalletConnectConnector({
      chains,
      options: {
        projectId: '...',
      },
    })
```
I get no desktop options:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/31530056/228021928-f50c9b03-d3d6-43d2-be66-227780734b09.png">

Additionally, `WalletConnect` on mobile shows no available options

### Expected Behavior

Wallet options are shown

**Comment by jxom** [comment]
I can't seem to reproduce this. Mind creating a minimal reproducible example via https://new.wagmi.sh? Will re-open when done.

**Comment by frankfka** [comment]
Ah @jxom here you go: https://stackblitz.com/edit/new-wagmi-zqvf6r?file=src/wagmi.ts

I found that it occurs when you use `arbitrumGoerli` and `goerli` as chains (which is the case for my usecase). I assume this is because Walletconnect V2 has no compatible desktop wallets for these chains?

**Comment by jxom** [comment]
Most likely those wallets don't support those chains yeah. @0xAsimetriq – can you confirm?
