### ISSUE TITLE
bug: "Chains must not be empty" using WalletConnect V2

### ISSUE THREAD

**Issue by mhm13dev** [wagmi-dev/references#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.10

### Current Behavior

I am using `wagmi` and `WalletConnectConnector` to create a custom QR Code using `display_uri`.

I get the `uri` and create a QR code from it.

When I scan it I get an error with message `Chains must not be empty`.

But when I use the same code with `WalletConnectLegacyConnector` from wagmi, then the wallet connects without any issues.

Error for V2:
![image](https://user-images.githubusercontent.com/28213822/230793836-202687c7-fa8d-43fb-9ecb-492ed155415a.png)

💥  And it is not only happening with me.
I just tested the Getting Started guide of [ConnectKit](https://github.com/family/connectkit) with `WalletConnectConnector` and it was showing the same error while it was working fine with `WalletConnectLegacyConnector`.

👉🏻 I am not sure if the issue is in wagmi's `WalletConnectConnector` or in [@walletconnect/ethereum-provider](https://www.npmjs.com/package/@walletconnect/ethereum-provider)

### Expected Behavior

Wallet Connect should not throw error `Chains must not be empty` and should connect successfully.

### Steps To Reproduce

client.ts
```typescript
import { configureChains, createClient } from "wagmi";
import { mainnet } from "wagmi/chains";
import { WalletConnectConnector } from "wagmi/connectors/walletConnect";
import { publicProvider } from "wagmi/providers/public";
import { Config } from "@/config";

const supportedChains = [mainnet];

const { chains, provider } = configureChains(supportedChains, [
  publicProvider(),
]);

export const wagmiClient = createClient({
  autoConnect: true,
  connectors: [
    new WalletConnectConnector({
      chains,
      options: {
        projectId: Config.Blockchain.WALLET_CONNECT_PROJECT_ID,
        showQrModal: false,
      },
    }),
  ],
  provider,
});
```

Context Providers
```typescript
"use client";

import { WagmiConfig } from "wagmi";
import { ConnectKitProvider } from "connectkit";
import { wagmiClient } from "@/web3/wagmi/client";

interface Props {
  children: React.ReactNode;
}

const Providers: React.FC<Props> = ({ children }) => {
  return (
    <>
      <WagmiConfig client={wagmiClient}>
        <ConnectKitProvider>{children}</ConnectKitProvider>
      </WagmiConfig>
    </>
  );
};

export default Providers;
```

Home Page
```typescript
"use client";

import { ConnectKitButton } from "connectkit";

export default async function Home() {
  return (
    <>
      <h1>Home</h1>

      <ConnectKitButton />
    </>
  );
}
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)
https://github.com/mhm13dev/wagmi-wallet-connect-v2

**Comment by jisensee** [comment]
> I can't seem to reproduce with the vanilla wagmi bootstrapped from `pnpm create wagmi`. Can you confirm what ConnectKit version you are on? Ideally, a minimal reproducible example (above comment) would be great so we can confirm the environment details.

I am having the same issue and can reproduce it with a standard bootstrapped wagmi project. II ran `npm create wagmi` and used the `Next.js` and `default` presets.

**Comment by glitch-txs** [comment]
you can set `"skipLibCheck": true` on tsconfig as workaround

**Comment by adeelibr** [comment]
Having the same issue with NextJS using default presets.

**Comment by adeelibr** [comment]
removing `chains` worked for me

```js
export const wagmiClient = createClient({
  autoConnect: true,
  connectors: [
    new WalletConnectConnector({
      options: {
        projectId: Config.Blockchain.WALLET_CONNECT_PROJECT_ID,
        showQrModal: false,
      },
    }),
  ],
  provider,
});
```

the problem is we are only passing `mainnet` to the list of chains, once we remove chains, the default chains list is included which includes all of it.

**Comment by m4kgsjd** [comment]
@adeelibr  thx, you saved my ass, but when we dont specify the chain we want to interact with, this error occurs;
```
witchChainError: Error switching chain
    at WalletConnectConnector.switchChain (walletConnect.js:166:1)
    at WalletConnectConnector.getProvider (walletConnect.js:132:1)
    at WalletConnectConnector.getSigner (walletConnect.js:137:1)
    at fetchSigner (chunk-VQG3VKOR.js:2865:1)
    at Object.queryFn4 [as queryFn] (index.js:779:21)
    at Object.fetchFn [as fn] (query.mjs:252:1)
    at run (retryer.mjs:101:1)
    at createRetryer (retryer.mjs:149:1)
    at Query.fetch (query.mjs:307:33)
    at QueryObserver.executeFetch (queryObserver.mjs:168:1)
    at QueryObserver.onSubscribe (queryObserver.mjs:28:1)
    at QueryObserver.subscribe (subscribable.mjs:12:1)
    at eval (index.js:174:1)
    at subscribeToStore (react-dom.development.js:16958:1)
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at eval (react-dom.development.js:26769:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
```
Have you tried to sendTransaction without configuring chain?

**Comment by m4kgsjd** [comment]
seems sendting transaction is not working without configuring chain...

**Comment by glitch-txs** [comment]
Does anyone has a minimal reproduction example of this? OP's one is abstracted with ConnectKit which makes it hard to debug unless looking into the source code of that version

**Comment by glitch-txs** [comment]
adding more than one chain seems to fix the issue as well

**Comment by abartolo** [comment]
I can also confirm, when having only 1 chain, I am getting "Chains must not be empty".

Once I added 2 chains(see below) I now get the following error:

New Error
```
react_devtools_backend_compact.js:2367 SwitchChainError: An error occurred when attempting to switch chain.

Details: Chain 'eip155:5' not approved. Please use one of the following: eip155:1
Version: viem@0.3.24
    at WalletConnectConnector.switchChain (walletConnect.js:208:13)
    at async WalletConnectConnector.getProvider (walletConnect.js:134:7)
    at async Promise.all (:3000/index 0)
    at async WalletConnectConnector.getWalletClient (walletConnect.js:138:33)
    at async getWalletClient (chunk-NRSD7F2O.js:1986:24)
```


Code that fixed "Chains must not be empty" error.
```
const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet, goerli], // Added additional chain for testing but I really just want 1 depending on environment
  [alchemyProvider({ apiKey: ALCHEMY_API_KEY }), publicProvider()],
);

```

**Comment by glitch-txs** [comment]
@abartolo that error means that the wallet doesn't support Goerli, you should add a different one, probably is a wallet that doesn't support testnet?

**Comment by glitch-txs** [comment]
@jxom @tmm I think I found the issue, might be related to a version update from ethereum-provider maybe.

optionalChains will throw 'Chains must not be empty' error if you pass an empty array, which wagmi's connector does if only one chain is selected in config.

```ts
const [defaultChain, ...optionalChains] = this.chains.map(({ id }) => id)
```

I've tested it in the latest version of wagmi, also using ethereum-provider alone.

```tsx
//pages/_app.tsx

import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import { createConfig, configureChains, mainnet, WagmiConfig } from 'wagmi'
import { publicProvider } from 'wagmi/providers/public'
import { WalletConnectConnector } from 'wagmi/connectors/walletConnect'
 
const { chains, publicClient } = configureChains([mainnet], [publicProvider()])
 
const config = createConfig({
  connectors: [
    new WalletConnectConnector({
      chains,
      options: {
        projectId: process.env.NEXT_PUBLIC_PROJECT_ID as string,
      },
    }),
  ],
  publicClient,
})

export default function App({ Component, pageProps }: AppProps) {
  return (    
    <WagmiConfig config={config}>
      <Component {...pageProps} />
    </WagmiConfig>
  )
}



// pages/index.tsx

import styles from '@/styles/Home.module.css'
import { useConnect } from 'wagmi'

export default function Home() {
  const { connect, connectors } = useConnect()
  return (
    <>
      <main className={styles.main}>
        {connectors.map(connector => <button key={connector.id} onClick={()=>connect({connector})} >{connector.name}</button>)}
      </main>
    </>
  )
}
```

**Comment by jxom** [comment]
Can't seem to reproduce it still... https://stackblitz.com/edit/new-wagmi-kcvslh?file=src%2Fwagmi.ts

**Comment by glitch-txs** [comment]
which wallet are you using for testing it? @jxom 
![image](https://github.com/wagmi-dev/references/assets/66949816/d21e44a2-2d17-4963-8271-f5f6622690cd)

**Comment by jxom** [comment]
Testing with Trust Wallet iOS & https://react-wallet-eip155-git-feat-examplesupgrade-walletconnect1.vercel.app/walletconnect

Does this happen after you connect, or before? Feeling it might be an issue with Trust Wallet's WalletConnect v2 implementation...

**Comment by glitch-txs** [comment]
I added the specs, but it mentions only required chains, it doesn't tell about optionalChains.
I'm on Android yes, this happens when scanning the QR code, it doesn't  get to connect

**Comment by jxom** [comment]
Might be worth getting in touch with Trust Wallet.

**Comment by 0xAsimetriq** [comment]
To anyone using android, make sure you are on their latest release. There was a build that errored when `optionalChains : []` were set to empty array, but this was fixed.

**Comment by glitch-txs** [comment]
@0xAsimetriq I'm on the latest on Trust Wallet, it says on play store last update was on May 26 🤔

**Comment by 0xAsimetriq** [comment]
@glitch-txs ty for info, asked them if build with fix was actually pushed up to play store. Meanwhile, this indeed seems to be an issue with trust wallet on android as opposed to wagmi.

**Comment by glitch-txs** [comment]
Thanks 👍

**Comment by abartolo** [comment]
> @abartolo that error means that the wallet doesn't support Goerli, you should add a different one, probably is a wallet that doesn't support testnet?

 @glitch-txs Good catch, I will need to try with another wallet that supports Goerli. I used Trust Wallet but only works with mainnet. Thank you!

**Comment by 2infinity-gh** [comment]
> @glitch-txs how can I connect on only chain bscTestnet. It still returns error "Chains must not be empty"

You could use NetworkWatch with NetworkSwitch to set the correct chain for your dApp

**Comment by gonzaotc** [comment]
I'm facing the same error, and the only way I found to bypass it is to pass two chains, (even if I only want to use one), otherwise, it throws this error.

**Comment by NanoInter** [comment]
The same error occurs when I use only one chain in Trust Wallet & Android.

**Comment by NanoInter** [comment]
I have escalated the issue to Trust Wallet support but they are not fixing the issue at all.
When I go into their Telegram chat room, I can't write and it's impossible to forward an issue to the developer community.
However, the inquiry email is changed to "Closed" and the issue is closed. Even when I ask why it was changed to "Closed", it only repeats the same answer.

Is there anyone who can contact the developer of Trust Wallet directly? I hope this will be solved but I'm already frustrated with Trust Wallet and I will tell my users not to use Trust Wallet in my project.

**Comment by glitch-txs** [comment]
@NanoInter this issue should be fixed on wagmi side, could you try to update to wagmi latest version?

**Comment by NanoInter** [comment]
> @NanoInter this issue should be fixed on wagmi side, could you try to update to wagmi's latest version?

I just tested again.
@wagmi/core Version 1.3.3 still gives the same error.

**Comment by glitch-txs** [comment]
@NanoInter kindly update to 1.3.7

**Comment by NanoInter** [comment]
@glitch-txs Updated to version 1.3.7.
At first I had a little trouble with the cache problem, but in the end the problem was solved!
thank you very much~
