### ISSUE TITLE
Coinbase wallets built using @ wagmi/core sometimes choose to cancel by default when the user does not proceed to the next step, resulting in the inability to proceed to the next step

### ISSUE THREAD

**Issue by youthinn** [wagmi-dev/references#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

Coinbase wallets built using @ wagmi/core sometimes choose to cancel by default when the user does not proceed to the next step, resulting in the inability to proceed to the next step。If login=>has not been clicked yet after calling Coinbase, the console has already prompted：
![image](https://github.com/wagmi-dev/wagmi/assets/96770326/02f2f53f-d38b-4efc-9ca2-148d2742cb89)

### Expected Behavior

希望能在用户确认操作后，再进行

**Comment by tmm** [comment]
I'm not able to reproduce this and we don't develop the Coinbase Wallet extension so probably best to follow up upstream with them.
