### ISSUE TITLE
bug: Error: No matching key. pairing: undefined

### ISSUE THREAD

**Issue by hlopes-ledger** [wagmi-dev/references#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

An error shows up on the browser console each time a user connects using the WalletConnect connector.
Connection seems to be established, not sure if it has any negative impact.
Happens on all browsers and wallet apps tested.

### Expected Behavior

No errors are shown on the console.

### Steps To Reproduce

Connect to any wallet using the WalletConnect (v2) connector.
The error shows up on the browser console.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/connect-wallet

### Anything else?

![image](https://github.com/wagmi-dev/wagmi/assets/106091551/3436383b-8abf-4ea2-a219-678054ec4b3a)

**Comment by tmm** [comment]
Please add a minimal reproduction so we can look into this.

**Comment by mhm13dev** [comment]
I am getting the same issue

**Comment by tmm** [comment]
@mhm13dev care to add a minimal reproduction?

**Comment by mhm13dev** [comment]
Clone this branch from the repo:
https://github.com/mhm13dev/wagmi-wallet-connect-v2/tree/pairing-error

Run the code.

Connect with Trust Wallet through Wallet Connect on Android and check console.

**Comment by mhm13dev** [comment]
@tmm

**Comment by drichar** [comment]
I'm seeing this error but I'm not using wagmi-dev. I'm using the standalone WalletConnect v2 sign client and an iOS Algorand wallet that's currently in development.

It also doesn't seem to affect a successful connection, but does appear every time a new pairing is created or an existing one is reconnected.

**Comment by drichar** [comment]
According to a WalletConnect collaborator it's being worked on and shouldn't affect SDK functionality: https://github.com/WalletConnect/web3modal-react-native/issues/38#issuecomment-1578963863

**Comment by DmitriiKholodov** [comment]
Hello, I am also facing with the same issue with my ReactJS web application

<img width="1791" alt="image" src="https://github.com/wagmi-dev/references/assets/28441549/748a1e3f-a106-4e2b-b422-a1324c3503b7">

I was trying to connect my TrustWallet (iOS Application) to my ReactJS web application.
Anyway, my wallet connected successfully despite this Error. But I want to deal with it.

If you want to get some extra information, please give me know which details you need.

**Comment by TimDaub** [comment]
This error appears to me when, immediately after `await writeAsync()` I call a hook that re-renders the page.

**Comment by paulobordignon** [comment]
I've changed something in my code and I also updated the following packages for these versions:
```
"@rainbow-me/rainbowkit": "^1.0.7",
"viem": "^1.3.1",
```
And the problem was solved.
