### ISSUE TITLE
bug: Type Error in `connectors/injected.ts`

### ISSUE THREAD

**Issue by zhuqingguang** [wagmi-dev/references#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Downloaded this repo and run `pnpm i` to install dependencies.
- Run `pnpm build` to build dist
- I get Error in `connectors/dist/injected.d.ts`:
![image](https://github.com/wagmi-dev/references/assets/24694223/7461e05e-77a6-4c71-b09d-7e1f28248ffb)

This behavior is stopping my project running.

### Expected Behavior

There is not type error and projects which used this package work fine.

### Steps To Reproduce

- Downloaded this repo and run `pnpm i` to install dependencies.
- Run `pnpm build` to build dist

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

**Here is a [repo](https://github.com/zhuqingguang/wagmi-type-error-repos)**

**Comment by glitch-txs** [comment]
as a workaround you can set `"skipLibCheck": false` to true on tsconfig

**Comment by zhuqingguang** [comment]
`skipLibCheck` works but others may don't want to use this config. Will the type error be fixed in the future?
