### ISSUE TITLE
bug: Unsupported wc_ method. wc_sessionPropose

### ISSUE THREAD

**Issue by BigtoLenaDev** [wagmi-dev/references#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.1

@web3modal/html: 2.4.5
@web3modal/ethereum: 2.4.5

### Current Behavior

1. Open the modal 
2. Scan QR code
3. The modal shows Connection declined, then failed to connect wallet
4. An error message also prints on console: `Unsupported wc_ method. wc_sessionPropose`

### Expected Behavior

After scan the QR code, wallet should connect successfully

### Steps To Reproduce

1. Setup Web3Modal
```javascript
import { Web3Modal } from "@web3modal/html";
import { EthereumClient, w3mConnectors, w3mProvider } from '@web3modal/ethereum'
import { publicProvider } from "@wagmi/core/providers/public";
import { InjectedConnector } from '@wagmi/core/connectors/injected'
import { configureChains, createConfig, getWalletClient } from "@wagmi/core";
import { WalletConnectConnector } from '@wagmi/core/connectors/walletConnect';

const setupConnectModal = () => {
    const projectId = process.env.WALLET_CONNECT_PROJECT_ID

    const { chains, publicClient, webSocketPublicClient } = configureChains(
        [polygon],
        [w3mProvider({ projectId }), publicProvider()]
    );
    const wagmiConfig = createConfig({
        autoConnect: true,
        connectors: [
            new InjectedConnector({
                chains,
                options: {
                    shimDisconnect: true
                }
            }),
            new WalletConnectConnector({
                chains: chains,
                options: {
                    projectId: projectId,
                    isNewChainsStale: true,
                },
            }),
            ...w3mConnectors({ chains, version: 2, projectId })
        ],
        publicClient,
        webSocketPublicClient
    });

    const ethereumClient = new EthereumClient(wagmiConfig, chains);

    const web3Modal = new Web3Modal(
        { projectId },
        ethereumClient
    )

    return web3Modal
}

export const ConnectModal = setupConnectModal()
```

2. Open the modal
```javascript
import { ConnectModal } from "xxx";

...

await ConnectModal.openModal()
```

### Anything else?

I can connect to my dapp if I use WalletConnect v1 `WalletConnectLegacyConnector` (@wagmi/core/connectors/walletConnectLegacy)

**Comment by glitch-txs** [comment]
Hey, seems like you're mixing two libraries, `@web3modal/html` and `@web3modal/ethereum` are from WalletConnect's Web3modal SDK. You only need what's in the docs for wagmi's WalletConnect config:
https://wagmi.sh/react/connectors/walletConnect

**Comment by tmm** [comment]
Thanks @glitch-txs! Closing for now.

**Comment by BigtoLenaDev** [comment]
> Hey, seems like you're mixing two libraries, `@web3modal/html` and `@web3modal/ethereum` are from WalletConnect's Web3modal SDK. You only need what's in the docs for wagmi's WalletConnect config: https://wagmi.sh/core/connectors/walletConnect

I tried uninstall `@web3modal/ethereum` and `@web3modal/html`, **ZERO** `@web3modal` dependency in my `package.json` file, and use below setup:
```javascript
export const walletConnectConnector = new WalletConnectConnector({
    chains: [polygon],
    options: {
        projectId: projectId,
        isNewChainsStale: true,
        showQrModal: true,
    },
})
```

another file:
```javascript
import { walletConnectConnector } from 'xxx'

const { address } = await connect({
    connector: walletConnectConnector
})
```

I'm still getting the same error, unable to connect wallet.

**Comment by tmm** [comment]
Please add a minimal reproducible example with instructions so we can help you.

**Comment by jxom** [comment]
What wallet are you interacting with?

**Comment by jxom** [comment]
What wallet are you interacting with?

**Comment by BigtoLenaDev** [comment]
> What wallet are you interacting with?

I use Infinity Wallet in my desktop.
But if I use Trust Wallet to scan the QR code, I got this error:

![image](https://github.com/wagmi-dev/references/assets/132535663/3ab5a332-5431-499d-88e8-d700ad677800)

**Comment by BigtoLenaDev** [comment]
any update please?
