### ISSUE TITLE
WalletConnect+TrustWallet: Invalid Session Properties requested

### ISSUE THREAD

**Issue by ThakerJayam** [wagmi-dev/references#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.13

### Current Behavior

OS: Android 11.
Platform: React
Using wagmi^0.12.13

After connecting to TrustWallet using WalletConnect, If I request a signature using
sign message from wagmi/actions,
following error is raised:
`{context: "client"} 'Invalid Session Properties requested'`.

### Expected Behavior

The sign message should return signature.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/ThakerJayam/test_wagmi

**Comment by sidagwl228** [comment]
Any update on this?

**Comment by zhengyimeng** [comment]
I'm using wagmi@^0.10.10, the same problem

**Comment by Encodtech** [comment]
Any solution to this?

**Comment by Encodtech** [comment]
I just solved this by adding 

`const topicId = JSON.parse(window.localStorage.getItem('topicId'));
    const session = await EthereumProvider.connect({
    requiredNamespaces: {
    eip155: {
    methods: ["eth_sendTransaction", "eth_requestAccounts", "eth_sign", "eth_accounts", "personal_sign"],
    chains: ["eip155:56"],
    events: ["connect", "disconnect","chainChanged", "accountsChanged"],
    pairingTopic: topicId,
    
    },
    },
    });`

In my EthereumProvider.init() function.

**Comment by Encodtech** [comment]
I just solved this by adding

const topicId = JSON.parse(window.localStorage.getItem('topicId'));
    const session = await EthereumProvider.connect({
    requiredNamespaces: {
    eip155: {
    methods: ["eth_sendTransaction", "eth_requestAccounts", "eth_sign", "eth_accounts", "personal_sign"],
    chains: ["eip155:56"],
    events: ["connect", "disconnect","chainChanged", "accountsChanged"],
    pairingTopic: topicId,
    
    },
    },
    });

To my EthereumProvider.init() function

**Comment by ThakerJayam** [comment]
@tmm Is there any update on this issue? 

Thanks!!
