### ISSUE TITLE
bug: <title>Migrating to WalletConnect v2

### ISSUE THREAD

**Issue by devi-000** [wagmi-dev/references#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm migrating to WalletConnect v2 and followed the steps mentioned in the documentation:
https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps#wagmi

I upgraded to "wagmi": "^0.12.0" (because I would like to keep using ethers) and included the walletConnectProjectId inside the config object for WalletConnectConnector.

Also, to use useWeb3Modal(), upgraded to "@web3modal/react": "^2.2.0".

### Expected Behavior

Are these changes enough? v1 is going to be dropped on June 28 and I want to make sure my users will still be able to connect to my dapp.

When I connect using MetaMaskConnector it works as expected, but when I try the WalletConnectConnector I'm not able to connect with any wallet by scanning the QR code. 

### Steps To Reproduce

Open the Link to Minimal Reproductible Example, click on "Connect to WalletConnect" button and then scan the QR code using a mobile wallet like MetaMask, TrustWallet.
On MetaMask I scan the code and then nothing happens.
On TrustWallet I get a popup saying "WalletConnect - Connecting may take a few seconds", but nothing happens.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/hardcore-solomon-778k2t?file=/src/App.js

**Comment by glitch-txs** [comment]
Hi, MetaMask doesn't support v2 yet, they are about to though. For Trust Wallet could you try updating to the last version?

**Comment by glitch-txs** [comment]
Hey, in the qrModalOptions object try adding this:
`explorerRecommendedWalletIds: 'NONE'`

All the options for that property you can check them here:
https://docs.walletconnect.com/2.0/web/web3modal/react/wagmi/options

**Comment by devi-000** [comment]
@glitch-txs since I'm using  "wagmi": "^0.12.0", the configureChains I have in the above example will work just fine after June 28, right? I just want to make sure the changes in the above example are the only changes I need. Thanks!

**Comment by glitch-txs** [comment]
Correct 👍

**Comment by devi-000** [comment]
@glitch-txs I just tested and I got a lot of errors. Please see attached images. Can you please tell me how to fix them? I only made the above changes. Also, when I click on the button to connect with 'wallet connect' I get the attached error in mutation.ts 
Is there a quick fix? What do you advice me to do? Thanks a lot!

![err1](https://github.com/wagmi-dev/references/assets/136474686/e24e6656-2b6e-4623-9d1d-4085d0040574)
![errors](https://github.com/wagmi-dev/references/assets/136474686/eb17a40d-d141-49f6-8c83-4b0b11573d7f)
![mutation-ts](https://github.com/wagmi-dev/references/assets/136474686/d99b711a-3885-40df-81be-6c42f92b3e0b)
