### ISSUE TITLE
bug: safe sdk having trouble with value-less write transactions

### ISSUE THREAD

**Issue by razgraf** [wagmi-dev/references#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using `prepareWriteContract` without an explicit `value` will work fine with most connectors except within a Safe environment. 

Note: I wasn't sure if I should publish this here, but figured it's best to keep it close to where the Safe SDK is being used.

### Expected Behavior

`prepareWriteContract` should count the optional value parameter (or `{value: undefined}`) as a non-payable transaction and proceed with the setup (e.g. simulateContract, ...) without trying to make use of that param.

### Steps To Reproduce

While `walletClient`s provided by regular connectors like Metamask will work fine and process the transaction flow, within Safe the transaction will fail with the following error:

![Screenshot 2023-06-15 at 23 37 11](https://github.com/wagmi-dev/references/assets/15740806/8b252ceb-f593-4047-9390-f0254e5fb8be)

As you can see, it attempts to convert `undefined` to what probably is an ethers.BigNumber instance used by the Safe SDK. 

A quick fix was to explicitly attribute `0n` to the value argument (no ETH passing through) in `prepareWriteContract`.

### Anything else?

Side-note: I imagine the Safe integration needs to be revisited in light of the viem update, as well as due to other issues such as https://github.com/wagmi-dev/wagmi/issues/2461

H/T @gavriliumircea

**Comment by jxom** [comment]
Should be fixed in `@wagmi/connectors@2.5.0` (the safe sdk viem upgrade)!
