### ISSUE TITLE
bug: WalletConnect instance missing setStorage method

### ISSUE THREAD

**Issue by jscriptcoder** [wagmi-dev/references#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm having a very strange issue that I cannot figure out and it's driving me crazy, so I'm hoping someone could shed some light on this. I'm using `Web3Modal`, which uses `w3mConnectors` as connectors. This, under the hood, creates an array with `InjectedConnector` and `WalletConnectConnector` (since I'm using version 2) as seen here: https://github.com/WalletConnect/web3modal/blob/V2/chains/ethereum/src/utils.ts#L35.

What's the problem? when I run this in my local all good (typical, right?). When I deploy this in Vercel, I get an exception because`WalletConnectConnector` instance is missing `setStorage` method, failing here: https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/config.ts#L124.

The only thing I can think of is that I'm pulling the wrong version of some package. See screenshot of the `walletConnect` instance in my local (first item of the list):
<img width="637" alt="Screenshot 2023-06-26 at 10 37 49" src="https://github.com/wagmi-dev/references/assets/613724/c268eba1-f8da-4355-8ea8-2c3f0b581af1">

Now see screenshot of `walletConnect` in Vercel:
<img width="647" alt="Screenshot 2023-06-26 at 10 46 26" src="https://github.com/wagmi-dev/references/assets/613724/9b9d9ee9-46b1-4b6c-8df8-fb172b1475f7">

Last one seems to have a slightly different interface, and if you go down the prototype, you don't see the method `setStorage`:
<img width="684" alt="Screenshot 2023-06-26 at 10 43 58" src="https://github.com/wagmi-dev/references/assets/613724/a10486a7-3433-46ad-abf2-5c7e02cf89d4">

Whereas in my local you see it:
<img width="668" alt="Screenshot 2023-06-26 at 10 44 34" src="https://github.com/wagmi-dev/references/assets/613724/9cea86dc-6431-48be-aa1c-eafc59bc2d20">

Both my local and Vercel are building the project using Node 18.x. Following is the list of dependencies:
```json
"dependencies": {
    "@wagmi/core": "^1.2.0",
    "@web3modal/ethereum": "^2.4.7",
    "@web3modal/html": "^2.4.7",
    "viem": "^1.0.7"
}
```

Please let me know if I can provide with some more information. What I'm hoping here is that someone might have an idea what the problem could be because I ran out of them.

### Expected Behavior

`WalletConnectConnector` instance extends Base connector, https://github.com/wagmi-dev/references/blob/e6fcfa938a95424a70f275409a6b620dfd7c980e/packages/connectors/src/base.ts, which contains the method `setStorage`

### Steps To Reproduce

N/A

### Anything else?

I'm testing in Chrome browser. The issue, as mentioned above, happens only when I deploy in Vercel. I don't have such issue when I run the dev environment nor when I run the production bundle in my local, so there must be something happening with the build on prod that might be pulling some wrong version?. I'm using Vite to build a SvelteKit project (Node 18.x). Following are the dev dependencies in case this is also needed:
```json
"devDependencies": {
    "@playwright/test": "^1.28.1",
    "@sveltejs/adapter-auto": "^2.0.0",
    "@sveltejs/adapter-static": "^2.0.2",
    "@sveltejs/kit": "^1.5.0",
    "@typescript-eslint/eslint-plugin": "^5.45.0",
    "@typescript-eslint/parser": "^5.45.0",
    "autoprefixer": "^10.4.14",
    "daisyui": "3.1.1",
    "eslint": "^8.28.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "eslint-plugin-svelte": "^2.26.0",
    "postcss": "^8.4.24",
    "prettier": "^2.8.0",
    "prettier-plugin-svelte": "^2.8.1",
    "svelte": "^3.54.0",
    "svelte-check": "^3.0.1",
    "tailwindcss": "^3.3.2",
    "tslib": "^2.4.1",
    "typescript": "^5.0.0",
    "vite": "^4.3.0",
    "vite-tsconfig-paths": "^4.2.0",
    "vitest": "^0.32.2"
}
```

Once again, I don't expect an answer to this issue, but some opinion. Thanks a lot

**Comment by glitch-txs** [comment]
Do you have the project ID set on Vercel?

**Comment by jscriptcoder** [comment]
Thanks for the answer @glitch-txs... I do, it's set. I changed the string to `'xxxxxxx...'` to take the screenshot. The only thing is that the domain hasn't yet been verified. Not sure if that could be the reason, and still I wouldn't understand why the interface of the walletConnect instance is different, like it seems to be an old one.

Thanks

**Comment by glitch-txs** [comment]
Do you have a minimal reproducible example repo to test it?

**Comment by jscriptcoder** [comment]
Hi @glitch-txs , the error can be seen here: https://taiko-mono-bridge-ui-v2.vercel.app/... I uploaded the source maps

Thanks

**Comment by jscriptcoder** [comment]
So it turned out that there was a problem with package versions. I removed `@wagmi/core`, and installed `wagmi` instead. See new dependencies:
```json
"dependencies": {
    "@web3modal/ethereum": "^2.6.2",
    "@web3modal/html": "^2.6.2",
    "viem": "^1.2.9",
    "wagmi": "^1.3.5"
}
```

This has fixed the problem 😊. Closing this ticket
