### ISSUE TITLE
bug: TypeError: EthereumProvider.init

### ISSUE THREAD

**Issue by w-toguchi83** [wagmi-dev/references#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
const connector = new WalletConnectConnector(...)
```

When running the code above, I encounter the following error in my environment:

`Uncaught (in promise) TypeError: EthereumProvider.init is not a function at WalletConnectConnector.initProvider_fn`

The library's exports and imports appear to be correct in the code, but for some reason, it doesn't work as expected in specific environments. The exact conditions causing this unexpected behavior are unknown. (I'm building the application using Rails + esbuild, but it doesn't have any particularly unusual configurations.)

In the problematic environment, the entire module is bound to EthereumProvider as default: EthereumProvider. Consequently, there is no init function available.

The following image is an examination of the return value of await import("@walletconnect/ethereum-provider"), which is executed within the library.
<img width="1173" alt="スクリーンショット 2023-06-27 16 51 28" src="https://github.com/wagmi-dev/references/assets/4586570/b716b3ed-74f6-4f13-a3de-3a260af79f50">

The problematic function in question is as follows.
https://github.com/wagmi-dev/references/blob/598d149657961271811ae3c18bbeae4c52a6a00c/packages/connectors/src/walletConnect.ts#L279-L310

### Expected Behavior

Ensure that the provider initialization can be performed without throwing the above exception: `Uncaught (in promise) TypeError: EthereumProvider.init is not a function at WalletConnectConnector.initProvider_fn`.

Please make the following specific changes to the code:

```
const {
  EthereumProvider,
  OPTIONAL_EVENTS,
  OPTIONAL_METHODS
} = await import("@walletconnect/ethereum-provider");
```

Since `EthereumProvider` is already exported from the module, I believe this modification should resolve the issue. In my local environment, making the above changes prevented the exception from occurring.

Unless there is a specific reason that requires `default: EthereumProvider`, please modify the code as indicated above.

### Steps To Reproduce

Unfortunately, I cannot identify specific steps or code snippets to reproduce the behavior.

The issue occurs in two Rails applications that I am involved with. However, it does not occur in another Rails application developed by my colleague.

To be honest, I have no idea what could be causing it. The issue persists even with other versions such as `0.10.10`.

It appears to be some form of environment dependency, but I am unsure.

### Anything else?

I'm not the only one struggling with the same exception. There are others who have encountered it as well:
https://github.com/orgs/WalletConnect/discussions/2687

To resolve this issue, I forked `wagmi`, made the necessary modifications locally, and used the built version with the fixes. Continuing to do this going forward is quite cumbersome.

Since it seems to be a minor fix, I kindly request you to make the necessary modifications.

**Comment by w-toguchi83** [comment]
I have solved this issue!

Conclusion: Behavior changes depending on the version of esbuild.

In my project, I use esbuild for JavaScript bundling in Rails. Upon checking, I found that the version of esbuild I was using was `0.14.36`.

When I changed it to the current latest version, which is `0.18.10`, and tried again, the `TypeError: EthereumProvider.init is not a function` error no longer occurred.

Here are the results I obtained after checking with each version of esbuild:

```
0.14.36 -> Not working
0.15.18 -> Not working

0.16.0 -> Working
0.16.17 -> Working
0.17.19 -> Working
0.18.10 -> Working
```

Such errors may also occur with other JS build tools. If you are facing the same problem, please try updating the version of your JS build tool to the latest one.

**Comment by oxSaturn** [comment]
Can confirm it happened as well when I ran my vitest tests. But I didn't run esbuild directly.

**Comment by oxSaturn** [comment]
@w-toguchi83 Pretty sure it's a misuse in the source code, just in case you're interested in why, see https://stackoverflow.com/a/76580524/22148155
