### ISSUE TITLE
bug: Issue with supported networks using WalletConnect v2

### ISSUE THREAD

**Issue by fonstack** [wagmi-dev/references#385]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

0.12.18

### Current Behavior

1. My dApp is not connected with any account. We have wagmi configured with multiple chains [mainnet, goerli, arbitrum, optimism, polygon].
2. I open the connector on the dApp (the WC v2 modal is opened)
3. I go to GnosisSafe wallet connect section (with a Safe Multisig on Goerli).
4. Copy the `connection link` from my dApp to WalletConnect.
5. Both sites (Safe and dApp) throws an error:
    ```
    Connection refused: Incompatible chain detected.
    Make sure the Dapp only uses Goerli to interact with this Safe.
    ```

If I try to do same thing but with a Safe multisig on mainnet, it works.

![CleanShot 2023-06-29 at 12 53 32](https://github.com/wagmi-dev/wagmi/assets/35873992/dfa190a2-b1a0-46d8-89f1-304b43c9ad7f)

### Expected Behavior

When no account connected on the dApp connect from any of the supported networks configured on wagmi.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-mtfvcu?file=src%2Fwagmi.ts

**Comment by marcossilvabr** [comment]
Likewise, I'm experiencing the exact same problem. Were you able to find a solution for it?

**Comment by glitch-txs** [comment]
This issue is being worked on
https://github.com/WalletConnect/walletconnect-monorepo/issues/2965

**Comment by fonstack** [comment]
What I'm doing (as a workaround) is to call the `connect()` function with `chainId` param.

`connect({ connector, chainId });`

**Comment by tmm** [comment]
If this issue still exists in the current version of Wagmi, please create a new issue on the [Wagmi repo](https://github.com/wagmi-dev/wagmi). Connectors are moving over there.
