### ISSUE TITLE
Attempt to connect to relay via `transportOpen` has stalled. Retrying

### ISSUE THREAD

**Issue by meetkosiso** [wagmi-dev/references#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0

### Current Behavior

I'm getting `Attempt to connect to relay via transportOpen has stalled. Retrying..` message sometimes when I try to load our website after we upgraded to wallet connect v2. However, this issue did not occur on wallet connect v1. 

### Steps To Reproduce

I expected to load our website without encountering this error message: `Attempt to connect to relay via `transportOpen` has stalled. Retrying..`

**Comment by Frontend-io** [comment]
Hey guys, this issue still happens repeatedly. I have no idea what causes it, but it just pops up randomly
I didn't perform any particular operation or action. 

<img width="1432" alt="image" src="https://github.com/wagmi-dev/references/assets/32682002/d46756e7-7a37-4f02-82ec-4fa4629f1b3f">

**Comment by kristiegiles** [comment]
Yup, I get the same error. 
<img width="370" alt="Screenshot 2023-07-11 at 3 18 50 PM" src="https://github.com/wagmi-dev/references/assets/25679998/a662581a-3356-4d10-800f-5ffd3da6bcc2">

This was an earlier error, so I'm guessing maybe the ws connection closed. 
<img width="361" alt="Screenshot 2023-07-11 at 3 19 38 PM" src="https://github.com/wagmi-dev/references/assets/25679998/aa47728b-e9db-4746-a871-e938f04616ad">

Possibly related:
https://github.com/WalletConnect/walletconnect-monorepo/issues/2970

**Comment by jxom** [comment]
Locking issue. Let’s keep WalletConnect related issues on the WalletConnect repositories.
