### ISSUE TITLE
bug: wagmi signMessage crash with error "Address "undefined" is invalid"

### ISSUE THREAD

**Issue by midotrinh1211** [wagmi-dev/references#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.3

### Current Behavior

The error related to message signing that (at the time-being) happens only on Bifrost mobile wallet (version `0.5.0`) while it works fine on mobile Metamask (version `v7.0.1`)

100% reproducible currently on your wagmi demo page: 
https://wagmi.sh/examples/sign-message

After connecting with WalletConnect, it always gets failed when signing message. 
However, if we reload the page, then message-sigining works fine again !!

<img width="938" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/41948347/efcf079c-f443-42c7-abf8-3ffd33bd26d2">

### Expected Behavior

Sign message must work.
It used to work fine with the WalletConnectLegacy !!

### Steps To Reproduce

Pls see the `Current behaviour`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/sign-message

### Anything else?

According to Bifrost,

The reason it works in metamask is because they return a approved session on this format:

```
{
  "namespaces": {
    "eip155": {
      "chains": ["eip155:14", "eip155:19"],
      "methods": ["eth_sendTransaction", "eth_signTransaction", "personal_sign"],
      "events": ["accountsChanged", "chainChanged"],
      "accounts": ["eip155:14:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb", "eip155:19:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb"]
    },
  }
}
```

While we return it on this format:

```
{
  "namespaces": {
    "eip155:14": {
      "methods": ["eth_sendTransaction", "eth_signTransaction", "personal_sign"],
      "events": ["accountsChanged", "chainChanged"],
      "accounts": ["eip155:14:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb"]
    },
    "eip155:19": {
      "methods": ["eth_sendTransaction", "eth_signTransaction", "personal_sign"],
      "events": ["accountsChanged", "chainChanged"],
      "accounts": ["eip155:19:0xab16a96d359ec26a11e2c2b3d8f8b8942d5bfcdb"]
    },
  }
}
```

**Comment by tmm** [comment]
If this issue still exists in the current version of Wagmi, please create a new issue on the [Wagmi repo](https://github.com/wagmi-dev/wagmi). Connectors are moving over there.
