### ISSUE TITLE
bug: Ethereum-provider throws error on empty array for optional chains

### ISSUE THREAD

**Issue by glitch-txs** [wagmi-dev/references#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems in the latest version of ethereum-provider now it won't allow you to set optionalChains as an empty array, which wagmi does when setting only one chain in the connector's config.
I wonder if the connector should be refactored? As we've also seen some wallets will "break" if the optionalChains is an empty array as well.

### Expected Behavior

no errors

### Steps To Reproduce

This error comes from ethereum-provider version `2.8.6`. I've tested using only this package and also with wagmi, both will throw an error when trying to open the modal.

the code for testing in ethereum-provider:

```tsx
    const client = await EthereumProvider.init({
      projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
      showQrModal: true,
      chains: [1],
      optionalChains:[], // <-- adding an empty array will throw an error
    });
```

Error on console:

```
Unsupported chains. connect() optionalNamespaces, chains must be defined as "namespace:chainId" e.g. "eip155:1": {...} in the namespace key OR as an array of CAIP-2 chainIds e.g. eip155: { chains: ["eip155:1", "eip155:5"] }
```

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/glitch-txs/wagmi-test

### Anything else?

pinging @0xAsimetriq for more insight

**Comment by wildlifechorus** [comment]
When will this be released?

**Comment by olegshilov** [comment]
@wildlifechorus 
> When will this be released?

Its already released. Try `wagmi:1.3.7`
