### ISSUE TITLE
bug: Network pulsechainV4 symbol is incorrect. Currently it is set at v4PLS it should be tPLS

### ISSUE THREAD

**Issue by hexlivelive** [wagmi-dev/references#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a user does not have the pulsechainV4 network in metamask and the application goes to auto add everything works okay but you get this warning message. "The submitted currency symbol does not match what we expect for the chain ID."

### Expected Behavior

No warning should happen

### Steps To Reproduce

Connect to http://test.mintra.pro without having the pulsechainV4 network configured. Click the button in the top right hand corner to connect to your wallet

**Comment by tmm** [comment]
Feel free to open a PR to fix
