### ISSUE TITLE
Socket stalled when trying to connect to wss://relay.walletconnect.com

### ISSUE THREAD

**Issue by poludnev** [wagmi-dev/references#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.8

### Current Behavior

Running my React application after Wagmi 1.xx release I faced a wss connection error which does not allow me to connect wallets on a mobile browser. 

I created a new and clear next app with the latest version of Wagmi + rainbow kit, and I have the same error: 

```
618.7d2d61445cdcb9a4.js:27 {context: 'core'} {context: 'core/relayer'} Error: WebSocket connection closed abnormally with code: 3000 (Authorization error: Unauthorized: invalid key)
    at s.onClose (618.7d2d61445cdcb9a4.js:27:42592)
    at i.<anonymous> (618.7d2d61445cdcb9a4.js:27:43229)
    at i.emit (_app-100d08ce6d27ffc2.js:7:29347)
    at k.onClose (618.7d2d61445cdcb9a4.js:1:20419)
    at e.onclose (618.7d2d61445cdcb9a4.js:1:20287)
```
```
618.7d2d61445cdcb9a4.js:1 Uncaught (in promise) Error: Socket stalled when trying to connect to wss://relay.walletconnect.com
    at _app-100d08ce6d27ffc2.js:1:97889
```
Connection to wallets in a mobile browser (ios, safari) doesn't work too. 

### Expected Behavior

Stable connection to Metamask/Rainbow wallet on mobile devices.

### Steps To Reproduce

1. git clone git@github.com:poludnev/wagmi-test.git
2. cd Wagmi-test
3. yarn install
4. yarn dev
5. Open localhost in a browser
6. Check the console

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi-test-git-main-poludnev.vercel.app/

### Anything else?

![image](https://github.com/wagmi-dev/wagmi/assets/51874367/4df97971-6be3-43e7-b251-295338988725)
![image](https://github.com/wagmi-dev/wagmi/assets/51874367/2ef41adf-bd29-424b-a2fa-dfc96aecfa45)

Deployed add: 
https://wagmi-test-git-main-poludnev.vercel.app/

Repo: 
https://github.com/poludnev/wagmi-test

**Comment by glitch-txs** [comment]
HI, you're missing the WalletConnect project ID, you need to create a Project in WalletConnect Cloud to get it:

https://www.rainbowkit.com/docs/installation#configure

**Comment by smartdevcom** [comment]
I got same issue even I set up project id

**Comment by Utcha** [comment]
I got same issue even I set up project id too

**Comment by glitch-txs** [comment]
hi @smartdevcom @Utcha by adding the Project ID in the given example I'm able to connect and I don't see that error, do you have any example that can reproduce the error?

**Comment by Shusanta** [comment]
@glitch-txs  place the wagmiconfig context anywhere not at the root, like in a sub component and you can see

**Comment by glitch-txs** [comment]
but you shouldn't do that, it needs to be declared once outside components

**Comment by Shusanta** [comment]
@glitch-txs  sure but what if I want to lazy load a modal that uses the walletconnect/web3 modal? Then I would have to move it down in some way. To avoid the bundle size impact

**Comment by glitch-txs** [comment]
This is already done by WalletConnect and Wagmi internally, also you'd need to check if there's an existing session in the client side

**Comment by Shusanta** [comment]
@glitch-txs on the checking the existing session-- could you direct me to any code that does that?

**Comment by glitch-txs** [comment]
WalletConnect does this on the init function of the ethereum-provider that's used by Wagmi, Wagmi also checks if there's a session saved on storage. Both of them lazy load the modal and the packages

**Comment by jxom** [comment]
The error is because you have not entered a valid WalletConnect Project ID. In the minimal reproducible example you provided, you can see the placeholder `YOUR_PROJECT_ID` variable is in the URL:  

<img width="677" alt="Screenshot 2023-08-14 at 8 55 41 pm" src="https://github.com/wagmi-dev/references/assets/7336481/e7ba3a41-a0ea-4cea-980f-6dfb37cd2b2c">

**Comment by kristiegiles** [comment]
> The error is because you have not entered a valid WalletConnect Project ID. In the minimal reproducible example you provided, you can see the placeholder `YOUR_PROJECT_ID` variable is in the URL:

@jxom The `Socket stalled when trying to connect to wss://relay.walletconnect.org` happens for me and others above with projectId defined. Should we make a separate issue?

```
<img width="1691" alt="Screenshot 2023-08-16 at 11 28 42 AM" src="https://github.com/wagmi-dev/references/assets/25679998/ab48aed1-1a0e-45b1-a156-ff2bf51b64ec">

**Comment by glitch-txs** [comment]
@kristiegiles hi, could you share an MRE?

**Comment by ChanchalD2022** [comment]
Experiencing the Same Issue. The Websocket connection stalls intermittently. The proposed solutions have been tried and failed. Kindly have a look

![Screenshot from 2023-08-17 20-06-46](https://github.com/wagmi-dev/references/assets/111080861/97a28571-ec67-442b-8255-28469feb25de)
![Screenshot from 2023-08-17 20-06-32](https://github.com/wagmi-dev/references/assets/111080861/64057710-62aa-4e57-878a-9926de69ed42)

**Comment by call3hudson** [comment]
Put your project id instead of YOUR_PROJECT_ID set by default.
