### ISSUE TITLE
CoinbaseWalletConnector - process is not defined

### ISSUE THREAD

**Issue by 58bits** [wagmi-dev/references#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

Following the example here... https://wagmi.sh/examples/connect-wallet - with MetaMaskConnector, CoinbaseWalletConnector, WalletConnectConnector, and InjectedConnector configured, CoinbaseWalletConnector is now returning an error on attempted connect...

`ReferenceError: process is not defined at at ../../node_modules/.pnpm/@coinbase+wallet-sdk@3.7.1/node_modules/@coinbase/wallet-sdk/dist/CoinbaseWalletSDK.js`

- I'm pretty sure this was working as recently as a few weeks ago. Note that this is a Remix run app - and the config has been adapted accordingly (look at `app/root.tsx`)

### Expected Behavior

Expect CoinbaseWalletConnector modal to be shown.

### Steps To Reproduce

Clone the example repo below followed by `npm install` and `npm run dev`. Injected, Metamask, and WalletConnect (if you provide a project id) connectors will all work. CoinbaseWalletConnector will return an error 'process is not defined.' and the CoinbaseWallet modal is not shown.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/infonomic/remix-wagmi-test

**Comment by tmm** [comment]
Upstream issue https://github.com/coinbase/coinbase-wallet-sdk/issues/874

**Comment by scotthconner** [comment]
Its also the same issue as this: https://github.com/coinbase/coinbase-wallet-sdk/issues/967
