### ISSUE TITLE
Update walletconnect to 2.9.1

### ISSUE THREAD

**Issue by imaksp** [wagmi-dev/references#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2.9.0 version is used.

### Expected Behavior

update to latest release which has some possible fixes related to ws socket timeout:
https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.9.1

**Comment by tmm** [comment]
Feel free to open a PR

**Comment by imaksp** [comment]
Hi, just added PR for this.
