### ISSUE TITLE
bug: Got "Oops! An error occurred" when using TrustWallet chrome extension for approve() function of ERC20

### ISSUE THREAD

**Issue by jingxuan98** [wagmi-dev/references#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Got "Oops! An error occurred" when using TrustWallet chrome extension for approve() function of ERC20
![Screenshot 2023-07-21 at 10 19 36 AM](https://github.com/rainbow-me/rainbowkit/assets/43902263/6eb6a32d-1ce3-4397-9829-7c38a20a6e5f)

When its other contract interaction, it works fine
![Screenshot 2023-07-21 at 10 18 24 AM](https://github.com/rainbow-me/rainbowkit/assets/43902263/418e1555-a499-47e3-9213-b98582027d75)

### Expected Behavior

Able to sign the approval txn successfully

### Steps To Reproduce

1. Try to sign a ERC20 approve() function

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

```
The way i initiate the ERC20 approve()

const token = TokenImplementation__factory.connect(tokenAddress, signer);
  return await (
    await token.approve(tokenBridgeAddress, amount, overrides)
  ).wait();
```

_No response_

**Comment by imaksp** [comment]
Are you sure that this is wagmi/viem's issue,? it could be due to some bug in beta trust wallet extension.
Have you tried calling it directly using ethereum.request or using other web3 lib?

**Comment by jxom** [comment]
This is a Trust Wallet issue. Best to get in touch with them.
