### ISSUE TITLE
bug: Getting "Invalid session properties" when requesting signature from trust wallet on mobile sometimes.

### ISSUE THREAD

**Issue by sidagwl228** [wagmi-dev/references#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On requesting signature from trust wallet using wagmi on mobile, it throws "Invalid session properties" error.
It happened with me 3-4 times repeatedly and after that it starts working perfectly fine.

### Expected Behavior

On requesting signature from trust wallet app, it should give me the desired signature hash and that too in the first try only.

### Steps To Reproduce

1. Go to https://wagmi.sh/examples/sign-message link on mobile.
2. Try to connect your trust wallet app with wagmi.
3. Then try signing a message.
4. Trust wallet will show sign message popup, which you have to accept.
5. On redirecting back to wagmi link, you will see an error saying: "Invalid session properties. Version: viem 1.0.0". Something along these lines.

### Anything else?

If I get this issue again, will attach the screenshot for sure.

Edit: Here is the screenshot of error.
![WagmiBug](https://github.com/wagmi-dev/references/assets/136440585/5247b86a-4f82-41b2-836c-fd9e269684a4)

**Comment by jxom** [comment]
Unfortunately this is an issue with Trust Wallet. Best to try and get in touch with them to resolve the issue.
