### ISSUE TITLE
bug: incorrect initialization of chains for WalletConnect V2 ethereum provider 

### ISSUE THREAD

**Issue by ElvisKrop** [wagmi-dev/references#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is applicable to the connection between any dapp that supports more than one network and wallet that doesn't support **the first network** from the list of supported networks by the previously mentioned dapp.

### Expected Behavior

WalletConnect Connector from Wagmi should not pass any chain id to the array of chains during initialization of WalletConnect. In this case all chain ids will be optional. I will allow to initiate the connection even if wallet supports on network from the list of supported networks by the dapp.

### At first let's go to the Revoke Cash:
1. open revoke.cash in one tab (it uses wagmi)
2. click "Connect Wallet"
3. choose "WalletConnect"

### The second part:
1. open app.safe.global
2. switch to any network supported by revoke.cash, except Ethereum mainnet
   - if you don't have any safe, you can use my safe on goerli for the demo - https://app.safe.global/home?safe=gor:0xB64b3B57B1c7bB6d69FAd705F01Eb60523355876
3. open WalletConnect safe app

### Then copy the connection link from Revoke Cash and paste on the pre-opened WalletConnect Safe App.

The error in console says:

> Connection refused: This Safe Account is in Goerli but the Wallet Connect session proposal is not valid because it contains: 1) A required chain different than Goerli 2) Does not include Goerli between the optional chains 3) No EVM compatible chain is included

### What happened:
WalletConnect Safe App is a safe app that allows to use safe as a wallet. However, each safe exists only on one network. Therefore WalletConnect Safe App initiates the connection with only one allowed network.
While dapp supports multiple networks. During initialization of WalletConnect connector from Wagmi dapp passes [all chain ids as an argument](https://github.com/RevokeCash/revoke.cash/blob/52afc3c0dabbd32c695f0901298e4c9400478c14/lib/hooks/ethereum/EthereumProvider.tsx#L60). Then Wagmi takes all these networks and [passes only the first chain id to the Ethereum provider from WalletConnect package](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/ethereum-provider/src/EthereumProvider.ts#L191). It is not correct, because **this array should include required chain ids** ([see the comment](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/ethereum-provider/src/EthereumProvider.ts#L191)):
> The Chains your app intents to use and the peer MUST support. If the peer does not support these chains, the connection will be rejected.
In our case the first chain id is 1 (Ethereum Mainnet), but we need 5 (Goerli Testnet)

**Comment by tmm** [comment]
If this issue still exists in the current version of Wagmi, please create a new issue on the [Wagmi repo](https://github.com/wagmi-dev/wagmi). Connectors are moving over there.
