### ISSUE TITLE
bug: "testnet: true" field is missing for Gnosis Chiado chain

### ISSUE THREAD

**Issue by begmaroman** [wagmi-dev/references#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/wagmi-dev/references/blob/main/packages/chains/src/gnosisChiado.ts#L3

`testnet: true` field is missing in the gnosis chiado chain config

### Expected Behavior

https://github.com/wagmi-dev/references/blob/main/packages/chains/src/gnosisChiado.ts#L3

`testnet: true` must be present

**Comment by tmm** [comment]
Chains should now be edited/added on the [Viem repository](https://github.com/wagmi-dev/viem). Feel free to edit over there.
