### ISSUE TITLE
bug: @wagmi/chains polygonMumbai default rpcUrl not working?

### ISSUE THREAD

**Issue by jaan1025** [wagmi-dev/references#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.0

### Current Behavior

cannot add mumbai chain to metamask
![image](https://github.com/wagmi-dev/wagmi/assets/22076610/18963542-0a14-4a34-be43-d69b5e46e5c0)

**Comment by danilo-89** [comment]
Chainstack has discontinued Polygon testnet & mainnet public RPC endpoints: https://twitter.com/ChainstackHQ/status/1682027531917234179

**Comment by vmichalik** [comment]
Hey, I opened a PR to fix this already #481 
It's pretty painful for teams who are building demo apps on mumbai right now. 

FWIW I've reached out to the Polygon team about fixing the issue with the wiki RPC but this one seems to work https://rpc-mumbai.polygon.technology/ and is what the matic.today link forwards to

**Comment by tmm** [comment]
See https://github.com/wagmi-dev/references/pull/481#issuecomment-1701602149
