### ISSUE TITLE
bug: autoConnect doesn't work for WalletConnect v2

### ISSUE THREAD

**Issue by maxaleks** [wagmi-dev/references#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.2

### Current Behavior

Wallet is not automatically connected when using WalletConnect v2.
With WalletConnect v1 it works as expected.

**Comment by jxom** [comment]
I can't seem to reproduce this. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox or a repository?

Can reopen when done!

**Comment by maxaleks** [comment]
I tried to create an example, but everything worked as expected. So the problem was on my end.
Sorry and thanks for the help!
