### ISSUE TITLE
bug: Dynamic import on walletconnect connector causes an error

### ISSUE THREAD

**Issue by omarsy** [wagmi-dev/references#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using wagmi walletConnect on vite, an error occurs. This error is caused by vite's use of dynamic import during its build process.

### Expected Behavior

I suggest memoizing this dynamic import, or converting it to a regular import: https://github.com/wagmi-dev/references/blob/5ed73ed2dc2a0e767ece992b9d0890d4513d5334/packages/connectors/src/walletConnect.ts#L312 

### Steps To Reproduce

1. Clone this project: https://github.com/jxom/create-wagmi-49
2. yarn build
3. yarn preview
4. Try to connect to the ledger => this will fail
5. Go to `vite.config.ts`
6.  add this to  disable the dynamic import ``` build: {
    rollupOptions: {
      output: {
        inlineDynamicImports: true,
      },
    },
  }```
7. yarn build
8. yarn preview
9. Try to connect with ledger it will work

### Anything else?

I try a fix: https://github.com/wagmi-dev/references/compare/main...omarsy:references:main

**Comment by tmm** [comment]
Not able to reproduce. If this issue still exists, please open a new issue against the latest version with a minimal reproduction.
